### ISSUE TITLE
Invisible character showing up on MAC

### ISSUE THREAD

**Issue by alexraskin** [engineer-man/felix#166]
This Invisible character is not invisible on mac.
https://github.com/engineer-man/felix/blob/addad2375bc46683c75674ba83acc04495526830/python/cogs/helpall.py#L24

[![Image from Gyazo](https://i.gyazo.com/6b0ec4c716ef1fef3ea681965b6bcaeb.png)](https://gyazo.com/6b0ec4c716ef1fef3ea681965b6bcaeb)

I tested just changing this to `" "` and it goes away, and it also works just fine on windows. 

[![Image from Gyazo](https://i.gyazo.com/2b6f01230e7fa9e63449e451a84a5704.png)](https://gyazo.com/2b6f01230e7fa9e63449e451a84a5704)

I can open a PR if that is what needs to happen!

**Comment by brtwrst** [comment]
"Working fine" is not quite accurate.
This is how it should look (and does on other platforms)
![Screenshot_20220205-073501_Discord.jpg](https://user-images.githubusercontent.com/6873862/152631593-9f4fe7ec-b765-465c-b833-852e3ef7ba32.jpg)
This Screenshot is from Android.

I don't have a Mac it so I can't look for a "fix" or another invisible character that accomplishes the same thing.

**Comment by alexraskin** [comment]
I should have been more clear, this is what it looks like on MAC:
[![Image from Gyazo](https://i.gyazo.com/6b0ec4c716ef1fef3ea681965b6bcaeb.png)](https://gyazo.com/6b0ec4c716ef1fef3ea681965b6bcaeb)

The invisible character is working as intended on every other device I have tested. 

Windows Example: [![Image from Gyazo](https://i.gyazo.com/0f808060f91555764eca331fe0364489.png)](https://gyazo.com/0f808060f91555764eca331fe0364489)

I understand discord removes white space, I am wondering if there is another invisible unicode character, that would play nice with MAC as well?

Thanks for your time. 👍

**Comment by xjzi** [comment]
The zero width space is now rendered on Linux in the browser, at least. 
![image](https://user-images.githubusercontent.com/66976878/167973374-85089aae-cd8e-4833-8ea5-a9ac5ba3e41d.png)
