### ISSUE TITLE
Notify team when # users join threshold is reached

### ISSUE THREAD

**Issue by zackoch** [engineer-man/felix#32]
If the number of users that join is say over 20 within 10 seconds, felix could notify @team with a formatted list of users. This would serve as a notification of some kind of flooding attempt, as well as an easy list to pass into a jail command. 

_Could auto jail too, but for streams and such it may be valid to get a huge amount of users at once joining._

Similar enhancement could just count the number of discord users in total, when threshold is reached felix broadcasts to @team "Hooray xxxxx number of discord users has been reached"

**Comment by brtwrst** [comment]
Implemented by #60
