### ISSUE TITLE
Add a Holiday Activity Task

### ISSUE THREAD

**Issue by brtwrst** [engineer-man/felix#59]
Add a task to the bot (preferrably general.py) that checks once per day (on or shortly after 00:00 UTC) if the current day is in a list of predefined holidays. This list can just be an instance variable or can be read from a holidays.json file.

If the current day is a holiday set the bot's activity to some predefined text specific to that holiday. If not set it back to the previous non-holiday activity.

example holiday list:
```
{
 "0704": "watching independance day 🇺🇸",
 "1003": "watching people being united 🇩🇪"
}
```

**Comment by Pyroseza** [comment]
Awesome idea Brtwst, are you gonna do this one yourself or is it open for one of us to do?

**Comment by solidassassin** [comment]
If he wanted to do it he would of already done it. The `Hacktoberfest` label pretty much tells that this is for everyone 😉 .

**Comment by Pyroseza** [comment]
Right, I did not know what the tag was for...
