### ISSUE TITLE
felix poll showing letters when it shouldn't

### ISSUE THREAD

**Issue by tipztek** [engineer-man/felix#6]
i did the following poll:

1. spend time on node.js basics series and do that each sunday for a while
2. integrating with someone's api (python)
3. real time chat client (node.js & socket.io)
4. job queue basics (python & dispenserd)
5. hashing vs encryption (theory)

and it gave me 1, 2, E, T, 3, 4, 5

it read e. in node.js and t. in socket.io as poll options

**Comment by brtwrst** [comment]
Fix was added to pull request.
