### ISSUE TITLE
Rename the 'Upload' command to 'Snippet'

### ISSUE THREAD

**Issue by dhdavvie** [engineer-man/felix#69]
As discussed during the PR #64, a more suitable name for the upload command would be 'snippet', so people would invoke it like `felix snippet [message_id]`. The name in the description menu would need to be changed, as well as the file name and method name I believe. 

If you need any help with this feel free to reach out :)

**Comment by brtwrst** [comment]
already done in 61a851a54d76b608b86590b710991688bc24978c and 49a114e00937966b17421956332cc8e6202003f6

**Comment by dhdavvie** [comment]
Ahh damn didn't notice, thanks!
