### ISSUE TITLE
Add message report function

### ISSUE THREAD

**Issue by DimitrisLK** [engineer-man/felix#84]
I think it will help with moderation of the server if you could message the bot with an **ID** or a **link** to a message violating server rules and the message being sent to the team for review.

**Comment by brtwrst** [comment]
How is that better than just alerting the team to the channel where the violation is happening?

**Comment by kevrocks67** [comment]
I have to agree with @brtwrst . A lot of times the problematic message needs to be viewed in context which means we end up going to the channel anyways.

**Comment by DimitrisLK** [comment]
I actually skipped over the "if you would like to get the attention of admins, you can type @engineer man team" part of the server rules and it wasn't clear to me who should be pinged.
 
I guess that makes this feature unnecessary.
