### ISSUE TITLE
Felix can jail himself

### ISSUE THREAD

**Issue by isakal** [engineer-man/felix#85]
Add a check if jail target is felix himself

**Comment by Nova-Ardent** [comment]
oh we're actually wanting to fix that?

**Comment by isakal** [comment]
i don't see why felix should be able to jail himself

**Comment by Nova-Ardent** [comment]
just seemed like a known shippable issue

**Comment by brtwrst** [comment]
Technically felix can't jail himself because he does not monitor his own messages for spamming.
A command can be given to felix by a select group of people that causes him to jail himself.

I see no problem with that.
