### ISSUE TITLE
Giphy does not work

### ISSUE THREAD

**Issue by manhoosbilli1** [engineer-man/felix#94]
Tried replacing giphy key in config file, didn't change work. it prints authors name and picture but not the gif itself. tried the same command 'felix gif sleeping' in Engineer man's discord server and got the same result.

**Comment by brtwrst** [comment]
works without issues for me

**Comment by Nova-Ardent** [comment]
works for me as well, ensure that your giphy api key is valid

**Comment by manhoosbilli1** [comment]
worked! just had to enable all image settings...
