### ISSUE TITLE
[felix run] Unexpected behavior when editing a new message with a `felix run` command.

### ISSUE THREAD

**Issue by TommyXR** [engineer-man/felix#96]
How to replicate:

* call `felix run`.

* Wait as much as you want

* Write a new message (unrelated to felix)

* Edit that message with a `felix run` command.

Felix will edit the output of the last "real" felix run command with the result.

**Comment by brtwrst** [comment]
that might be unexpected but is totally how i implemented it.

the fix for that is actually quite easy now that i think about it
